<?php

namespace TcbManager;

class Constants {
    const ENV_SECRETID      = "TENCENTCLOUD_SECRETID";
    const ENV_SECRETKEY     = "TENCENTCLOUD_SECRETKEY";
    const ENV_SESSIONTOKEN  = "TENCENTCLOUD_SESSIONTOKEN";
    const ENV_TCB_ENV_ID    = "TENCENTCLOUD_TCB_ENVID";
    const ENV_RUNENV        = "TENCENTCLOUD_RUNENV";
    const ENV_RUNENV_SCF    = "TENCENTCLOUD_RUNENV=SCF";
}
